### PR TITLE
Fixes windows builds

### PR DESCRIPTION
**Pull request by madebr**
This *should* also fix the Linux failures.

### CODE REVIEW

**Comment by vcampmany** [comment]
@madebr thanks for the fixes. I checked out the branch locally and the linking of the test package fails with the following error (tested with clang and gcc):
```
/usr/bin/ld: /lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
```
Adding the following line to the `package_info` method solves the issue
```
self.cpp_info.components["libjsonnet"].system_libs.append("m")
```
I'm wondering, do you experience the same issue?

Regarding the fixes for the Linux failures, could you point out the lines that fix the issues, I'm curious. Thanks again for pushing the PR forward!

**Comment by madebr** [comment]
I just didn't test it on Linux. I was working on Windows to fix some other recipes.
You need to add the the system library only for linux and freebsd:
```python
if self.settings.os in ("FreeBSD", "Linux"):
    self.cpp_info.components["libjsonnet"].system_libs.append("m")
```

**Comment by madebr** [comment]
> Regarding the fixes for the Linux failures, could you point out the lines that fix the issues, I'm curious. Thanks again for pushing the PR forward!

Conan 1.x needs the `cmake` generator (`conanbuildinfo.cmake`) to set the correct c/cxx/linker flags.
You were doing `self._cmake.configure(build_folder=self._build_subfolder, source_folder=self._source_subfolder)` which circumvents the cmake wrapper.
Because of this, you were using your default (recent) gcc compiler which is `libstdc++11`.

Conan 2.0 should change this by using cmake toolchain files + other features.

(I also rewrote your pathces because I thought they were too "heavy")

**Comment by madebr** [comment]
I didn't look deep into the `validate` method.
But if you raised the minimum required compiler version because of build failures on c3i,
then you can consider to remove that check (or lower the required compiler version)

**Comment by vcampmany** [comment]
Thanks @madebr , I will merge this one and take a look at the `validate` method and fix the system libraries in Linux an FreeBSD.

**Pull request merged**
